#!/usr/bin/bash

launchctl_mgr() {
	failure() {
		local lineno=$1
		local msg=$2
		echo "Failed at $lineno: $msg"
	}
	trap 'failure ${lineno} "$BASH_COMMAND"' ERR
	trap 'trap - ERR' RETURN

	local instruction="$1"
	local filepath="$2";
	#test whether the file argument is already a file or not and whether or not it is actually a path
	if [[ ! -f $filename ]]
	then
		if [[ -f ~/Library/LaunchAgents/$filepath.plist ]]
		then
			filepath="$HOME/Library/Launchagents/$filepath.plist"
			echo "found!: $filepath"
		elif [[ -f /Library/LaunchAgents/$2.plist ]]
		then
			filepath="/Library/LaunchAgents/$filepath.plist"
		else
			echo "Filename supplied was not valid as a launchagent"
			return 1
		fi
	fi
	if [[ $instruction == "restart" || $instruction == "unload" ]]
	then
		echo "instruction is $instruction"
		echo "filepath is $filepath"
		launchctl unload "$filepath" 2>&1
		if [[ $instruction == "restart" ]]
		then
			launchctl load "$filepath"
			launchctl start "$filepath"
		fi
	else
		echo "Unrecognised command name"
		return 1
	fi
}
